version: '3.8'
services:
  app:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    depends_on:
      - postgres
  nginx:
    image: nginx:latest
    container_name: guest-nginx
    ports:
      - "8080:50"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: guests
      POSTGRES_USER: guest_user
      POSTGRES_PASSWORD: topsecret
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: